apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: orders
data:
  APP_NAME: orders-api
  APP_PORT: "8000"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: orders_db
  KAFKA_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc:9092"
