apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: orders-api:local
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: APP_NAME
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: APP_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: POSTGRES_PORT
            - name: KAFKA_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: KAFKA_ENABLED
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10