apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: test.rules
      rules:
        - alert: TestAlwaysFiring
          expr: vector(1)
          labels:
            severity: warning
          annotations:
            summary: "Test alert"
            description: "This is a test alert"